blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Blog:index }

blog_new:
    path:     /register
    defaults: { _controller: BlogBundle:Blog:register }

blog_new_post:
    path:     /new
    defaults: { _controller: BlogBundle:Crud:new }
    
blog_view:
    path:     /{id}
    defaults: { _controller: BlogBundle:Blog:blog }

blog_view_post:
    path:     /post/{id}
    defaults: { _controller: BlogBundle:Blog:post }

blog_edit_post:
    path:     /edit/{id}
    defaults: { _controller: BlogBundle:Crud:edit }

blog_delete_post:
    path:     /delete/{id}
    defaults: { _controller: BlogBundle:Crud:delete }