blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Blog:index }

blog_new_user:
    path:     /register
    defaults: { _controller: BlogBundle:Blog:register }

blog_new:
    path:     /new
    defaults: { _controller: BlogBundle:Blog:new }

blog_edit:
    path:     /edit/{url_blog}
    defaults: { _controller: BlogBundle:Blog:edit }

blog_view:
    path:     /{url_blog}
    defaults: { _controller: BlogBundle:Blog:blog }

blog_new_post:
    path:     /{url_blog}/new
    defaults: { _controller: BlogBundle:Crud:new }

blog_edit_post:
    path:     /{url_blog}/edit/{url_post}
    defaults: { _controller: BlogBundle:Crud:edit }

blog_delete_post:
    path:     /{url_blog}/delete/{url_post}
    defaults: { _controller: BlogBundle:Crud:delete }

blog_view_post:
    path:     /{url_blog}/{url_post}
    defaults: { _controller: BlogBundle:Blog:post }