blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Blog:index }

blog_search:
    path:     /search/{search}
    defaults: { _controller: BlogBundle:Blog:search, search: "" }

blog_new_user:
    path:     /register
    defaults: { _controller: BlogBundle:Blog:register }

blog_new:
    path:     /new
    defaults: { _controller: BlogBundle:Blog:new }

blog_edit:
    path:     /edit/{url_blog}
    defaults: { _controller: BlogBundle:Blog:edit }

blog_delete:
    path:     /delete/{url_blog}
    defaults: { _controller: BlogBundle:Blog:delete }

blog_view:
    path:     /{url_blog}/{page}
    defaults: { _controller: BlogBundle:Blog:blog, page: 1 }
    requirements:
        page:  \d+

blog_new_post:
    path:     /{url_blog}/new
    defaults: { _controller: BlogBundle:Crud:new }

blog_new_category:
    path:     /{url_blog}/new-category
    defaults: { _controller: BlogBundle:Blog:newCategory }

blog_edit_category:
    path:     /{url_blog}/edit-category/{category_name}
    defaults: { _controller: BlogBundle:Blog:editCategory }

blog_delete_category:
    path:     /{url_blog}/delete-category/{category_name}
    defaults: { _controller: BlogBundle:Blog:deleteCategory }

blog_view_by_category:
    path:     /{url_blog}/{category_name}/{page}
    defaults: { _controller: BlogBundle:Blog:blog, page: 1 }
    requirements:
        page:  \d+

blog_edit_post:
    path:     /{url_blog}/edit/{url_post}
    defaults: { _controller: BlogBundle:Crud:edit }

blog_delete_post:
    path:     /{url_blog}/delete/{url_post}
    defaults: { _controller: BlogBundle:Crud:delete }

blog_view_post:
    path:     /{url_blog}/{category_name}/{url_post}/{page}
    defaults: { _controller: BlogBundle:Blog:post, page: 1 }
    requirements:
        page:  \d+
