<?php

namespace FlorianMasip\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Récupère les derniers blogs
     *
     * @param int $nb
     * @return Paginator
     */
    public function getLastCreatedBlogs($nb = 5) {

        $q = $this->_em->createQueryBuilder()
                ->select('blog')
                ->from('BlogBundle:Blog', 'blog');

        $q->setMaxResults($nb);

        return new Paginator($q);
    }

}
