<?php

namespace FlorianMasip\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{

    /**
     * Récupère une liste des catégorys selon un nom de catégory
     * @param string $unNomCategory
     * @return array
     */
    public function findAllByNomCategory($unNomCategory = null) {

        if ($unNomCategory != null) {
            return $this->getEntityManager()
                            ->createQuery(
                'SELECT p
                FROM BlogBundle:Category p
                WHERE p.nom = :nomCat
                ORDER BY p.nom ASC')->setParameter('nomCat', $unNomCategory)->getResult();
        } else {
            return $this->getEntityManager()
                            ->createQuery(
                'SELECT p
                FROM BlogBundle:Category p
                ORDER BY p.nom ASC')->getResult();
        }

    }

    /**
     * Récupère la liste des catégories d'un blog
     * @param Blog blog
     * @return array
     */
    public function findByBlogOrdered($blog) {

        return $this->getEntityManager()
                        ->createQuery(
            'SELECT c
            FROM BlogBundle:Category c
            WHERE c.blog = :blog
            ORDER BY c.nom ASC')
            ->setParameter('blog', $blog)
            ->getResult();
    }
}
